apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-data
  labels:
    app: uptime-kuma
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
